services:
    nginx:
        image: nginx:stable
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    php:
        build:
            context: ./.docker
            dockerfile: /Dockerfile
        volumes:
            - ./:/var/www/html
        ports:
            - "9000:9000"

    mysql:
        image: mysql:8.0.29-oracle
        ports:
            - "3307:3306"
        volumes:
            - ./.docker/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel_portfolio_docker
            MYSQL_USER: anhquoc
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "8081:80"
        environment:
            - PMA_HOSTS=mysql
            - PMA_PORT=3306
            - PMA_USER=root
            - PMA_PASSWORD=${DB_PASSWORD}
